<div class="barangay-bansud">
<option value="" disabled selected>Select Barangay</option>
    <option value="Alcadesma">Alcadesma</option>
    <option value="Bato">Bato</option>
    <option value="Conrazon">Conrazon</option>
    <option value="Malo">Malo</option>
    <option value="Manihala">Manihala</option>
    <option value="Pag-asa">Pag-asa</option>
    <option value="Poblacion">Poblacion</option>
    <option value="Proper Bansud">Proper Bansud</option>
    <option value="Proper Tiguisan">Proper Tiguisan</option>
    <option value="Rosacara">Rosacara</option>
    <option value="Salcedo">Salcedo</option>
    <option value="Sumagui">Sumagui</option>
    <option value="Villa Pag-asa">Villa Pag-asa</option>
</div>


<div class="barangay-gloria">
    <option value="" disabled selected>Select Barangay</option>
    <option value="Agos">Agos</option>
    <option value="Agsalin">Agsalin</option>
    <option value="Alma Villa">Alma Villa</option>
    <option value="Andres Bonifacio">Andres Bonifacio</option>
    <option value="Balete">Balete</option>
    <option value="Banus">Banus</option>
    <option value="Banutan">Banutan</option>
    <option value="Bulaklakan">Bulaklakan</option>
    <option value="Buong Lupa">Buong Lupa</option>
    <option value="Gaudencio Antonino">Gaudencio Antonino</option>
    <option value="Guimbonan">Guimbonan</option>
    <option value="Kawit">Kawit</option>
    <option value="Lucio Laurel">Lucio Laurel</option>
    <option value="Macario Adriatico">Macario Adriatico</option>
    <option value="Malamig">Malamig</option>
    <option value="Malayong">Malayong</option>
    <option value="Maligaya">Maligaya</option>
    <option value="Malubay">Malubay</option>
    <option value="Manguyang">Manguyang</option>
    <option value="Maragooc">Maragooc</option>
    <option value="Mirayan">Mirayan</option>
    <option value="Narra">Narra</option>
    <option value="Papandungin">Papandungin</option>
    <option value="San Antonio">San Antonio</option>
    <option value="Santa Maria">Santa Maria</option>
    <option value="Santa Theresa">Santa Theresa</option>
    <option value="Tambong">Tambong</option>
</div>


<div class="barangay-pinamalayan">
<option value="" disabled selected>Select Barangay</option>
    <option value="Anoling">Anoling</option>
    <option value="Bacungan">Bacungan</option>
    <option value="Bangbang">Bangbang</option>
    <option value="Banilad">Banilad</option>
    <option value="Buli">Buli</option>
    <option value="Cacawan">Cacawan</option>
    <option value="Calingag">Calingag</option>
    <option value="Del Razon">Del Razon</option>
    <option value="Guinhawa">Guinhawa</option>
    <option value="Inclanay">Inclanay</option>
    <option value="Lumangbayan">Lumangbayan</option>
    <option value="Malaya">Malaya</option>
    <option value="Maliangcog">Maliangcog</option>
    <option value="Maningcol">Maningcol</option>
    <option value="Marayos">Marayos</option>
    <option value="Marfrancisco">Marfrancisco</option>
    <option value="Nabuslot">Nabuslot</option>
    <option value="Pagalagala">Pagalagala</option>
    <option value="Palayan">Palayan</option>
    <option value="Pambisan Malaki">Pambisan Malaki</option>
    <option value="Pambisan Munti">Pambisan Munti</option>
    <option value="Panggulayan">Panggulayan</option>
    <option value="Papandayan">Papandayan</option>
    <option value="Pili">Pili</option>
    <option value="Quinabigan">Quinabigan</option>
    <option value="Ranzo">Ranzo</option>
    <option value="Rosario">Rosario</option>
    <option value="Sabang">Sabang</option>
    <option value="Santa Isabel">Santa Isabel</option>
    <option value="Santa Maria">Santa Maria</option>
    <option value="Santa Rita">Santa Rita</option>
    <option value="Santo Niño">Santo Niño</option>
    <option value="Wawa">Wawa</option>
    <option value="Zone I">Zone I</option>
    <option value="Zone II">Zone II</option>
    <option value="Zone III">Zone III</option>
    <option value="Zone IV">Zone IV</option>
</div>